apiVersion: v1
kind: Secret
metadata:
  name: {{ include "configarr.fullname" . }}
  labels:
    {{- include "configarr.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets.yml: |
    {{- range $key, $value := .Values.secrets.data }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
